"""Generate src/format/MoveCategoryLocs.inc: loc id -> movement category.

The artifact keeps a transition's loc id and option index but not the loc's
name or the option's text, and those are what tell a door from a stile from an
agility shortcut. This script reads the curated transport links and the loc
definitions dumped from the cache, names each curated loc's category by its
name and the text of the option the row clicks, and writes the ids as a sorted
table the runtime classifier (src/format/MoveCategory.cpp) searches.

Only curated locs need an entry. A loc that no row names (the doors, ladders
and stairs the bake derives from the cache) is classified by geometry alone.

    python tools/move_categories/gen_move_locs.py <locations.json> [datasets dir]

<locations.json> is a cache loc dump: a JSON array of {id, name, actions[]},
with // comments allowed. Re-run after editing transport_links.json.
"""

import collections
import json
import pathlib
import re
import sys

# Category names as in format::MoveCategory (and WW_MOVE_* in worldwalker_c.h).
DOORS, SHORTCUTS, PLANE, CLIMBOVERS, TRANSPORTS = 'Doors', 'Shortcuts', 'Plane', 'ClimbOvers', 'Transports'
FAIRY_RINGS, SPIRIT_TREES = 'FairyRings', 'SpiritTrees'

PLANE_ACTIONS = {'climb-up', 'climb-down', 'climb up', 'climb down', 'climb-top',
                 'climb-bottom', 'ascend', 'descend', 'walk-up', 'walk-down',
                 'climb top floor', 'climb bottom floor', 'top floor', 'bottom floor'}
PLANE_NAMES = ('ladder', 'stair', 'trapdoor', 'trap door')
DOOR_NAMES = ('door', 'gate', 'portcullis', 'curtain', 'barrier')
DOOR_ACTIONS = {'open', 'go-through', 'walk-through', 'walk through', 'pass-through',
                'pass through', 'pick-lock', 'unlock'}
SHORTCUT_ACTIONS = {'jump', 'jump-across', 'jump across', 'jump-from', 'jump-down',
                    'squeeze-through', 'squeeze-past', 'balance on', 'balance',
                    'swing-on', 'swing across', 'walk-across', 'traverse', 'climb',
                    'crawl-through', 'cross', 'slash', 'chop-down', 'chop down', 'pass',
                    'lift', 'slide', 'grab', 'grapple'}
# Isafdar's forest obstacles: entered, not opened, and an agility course in all
# but name.
SHORTCUT_NAMES = ('dense forest',)


def category(name, action, hop):
    """The category a curated row's loc belongs to, or None to leave it to
    the runtime's geometry."""
    n = (name or '').lower()
    a = (action or '').lower()
    if 'fairy ring' in n:
        return FAIRY_RINGS
    if 'spirit tree' in n:
        return SPIRIT_TREES
    if a in PLANE_ACTIONS or any(k in n for k in PLANE_NAMES):
        return PLANE
    if 'over' in a or 'stile' in n or 'wilderness wall' in n:
        return CLIMBOVERS
    near = hop <= 4
    if near and (a in DOOR_ACTIONS or any(k in n for k in DOOR_NAMES)):
        return DOORS
    if a in SHORTCUT_ACTIONS or any(k in n for k in SHORTCUT_NAMES):
        return SHORTCUTS
    return TRANSPORTS


def load_locs(path):
    text = pathlib.Path(path).read_text(encoding='utf-8')
    text = re.sub(r'\s//[^\n]*', '', text)
    return {o['id']: (o.get('name'), o.get('actions') or []) for o in json.loads(text)}


def main():
    locs = load_locs(sys.argv[1])
    datasets = pathlib.Path(sys.argv[2] if len(sys.argv) > 2 else 'datasets')
    rows = json.loads((datasets / 'transport_links.json').read_text(encoding='utf-8'))
    votes = collections.defaultdict(collections.Counter)
    for r in rows:
        if r.get('disabled') or r.get('npc') or r['object_id'] <= 0:
            continue
        name, actions = locs.get(r['object_id'], (None, []))
        index = r['option_index']
        action = actions[index] if index < len(actions) else None
        hop = max(abs(r['x'] - r['dest_x']), abs(r['y'] - r['dest_y']))
        votes[r['object_id']][category(name, action, hop)] += 1
    out = pathlib.Path(__file__).resolve().parents[2] / 'src' / 'format' / 'MoveCategoryLocs.inc'
    lines = ['// GENERATED by tools/move_categories/gen_move_locs.py -- do not edit by hand.',
             '// { loc id, MoveCategory } for every loc a curated transport link clicks,',
             '// sorted by id. See MoveCategory.cpp.']
    conflicts = 0
    for loc_id in sorted(votes):
        best, _ = votes[loc_id].most_common(1)[0]
        conflicts += 1 if len(votes[loc_id]) > 1 else 0
        lines.append(f'{{ {loc_id}, MoveCategory::{best} }},')
    out.write_text('\n'.join(lines) + '\n', encoding='ascii', newline='\n')
    counts = collections.Counter(v.most_common(1)[0][0] for v in votes.values())
    print(f'{len(votes)} locs ({conflicts} with rows in more than one category) -> {out}')
    for k, v in counts.most_common():
        print(f'  {k}: {v}')


if __name__ == '__main__':
    main()
